from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import re
import os


# Brand colors
BLACK = HexColor("#0a0a0a")
YELLOW = HexColor("#e8ff47")
WHITE = HexColor("#ffffff")
GRAY = HexColor("#888888")
LIGHT_GRAY = HexColor("#cccccc")


def clean_markdown(text: str) -> str:
    """Remove markdown symbols for plain text rendering."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"#{1,6}\s*", "", text)
    return text.strip()


def generate_report_pdf(report_text: str, creator_name: str = "Creator") -> str:
    """
    Generates a branded PDF report from the creator report text.

    Args:
        report_text: The full report text from Gemini
        creator_name: Name of the creator for the report

    Returns:
        Path to the generated PDF file
    """
    os.makedirs("outputs", exist_ok=True)
    safe_name = creator_name.replace(" ", "_").lower()
    output_path = f"outputs/{safe_name}_reelify_report.pdf"

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "Title",
        fontSize=28,
        fontName="Helvetica-Bold",
        textColor=BLACK,
        spaceAfter=4,
        alignment=TA_LEFT,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        fontSize=12,
        fontName="Helvetica",
        textColor=GRAY,
        spaceAfter=20,
        alignment=TA_LEFT,
    )

    section_header_style = ParagraphStyle(
        "SectionHeader",
        fontSize=14,
        fontName="Helvetica-Bold",
        textColor=BLACK,
        spaceBefore=20,
        spaceAfter=8,
        borderPad=6,
    )

    body_style = ParagraphStyle(
        "Body",
        fontSize=10,
        fontName="Helvetica",
        textColor=HexColor("#333333"),
        spaceAfter=6,
        leading=16,
        alignment=TA_LEFT,
    )

    bullet_style = ParagraphStyle(
        "Bullet",
        fontSize=10,
        fontName="Helvetica",
        textColor=HexColor("#333333"),
        spaceAfter=4,
        leading=15,
        leftIndent=16,
        bulletIndent=4,
    )

    label_style = ParagraphStyle(
        "Label",
        fontSize=8,
        fontName="Helvetica-Bold",
        textColor=GRAY,
        spaceAfter=2,
        letterSpacing=1,
    )

    story = []

    # ── Header ──
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("⚡ REELIFY", ParagraphStyle(
        "Brand",
        fontSize=11,
        fontName="Helvetica-Bold",
        textColor=BLACK,
        spaceAfter=16,
    )))
    story.append(Paragraph(f"Creator Strategy Report", title_style))
    story.append(Paragraph(f"Prepared for {creator_name}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=BLACK, spaceAfter=20))

    # ── Parse and render report sections ──
    lines = report_text.split("\n")
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        if not line:
            story.append(Spacer(1, 0.08 * inch))
            i += 1
            continue

        # Section headers (## or ###)
        if line.startswith("##"):
            text = clean_markdown(line)
            story.append(Spacer(1, 0.1 * inch))
            story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#e0e0e0"), spaceAfter=8))
            story.append(Paragraph(text, section_header_style))
            i += 1
            continue

        # Numbered items (1. 2. 3.)
        if re.match(r"^\d+\.\s", line):
            text = clean_markdown(line)
            story.append(Paragraph(f"• {text}", bullet_style))
            i += 1
            continue

        # Bullet points
        if line.startswith("*") or line.startswith("-"):
            text = clean_markdown(line.lstrip("*- ").strip())
            if text:
                story.append(Paragraph(f"• {text}", bullet_style))
            i += 1
            continue

        # Regular paragraph
        text = clean_markdown(line)
        if text:
            story.append(Paragraph(text, body_style))
        i += 1

    # ── Footer ──
    story.append(Spacer(1, 0.4 * inch))
    story.append(HRFlowable(width="100%", thickness=1, color=HexColor("#e0e0e0"), spaceAfter=12))
    story.append(Paragraph(
        "Generated by Reelify · AI-powered content strategy for micro creators",
        ParagraphStyle("Footer", fontSize=8, fontName="Helvetica", textColor=GRAY, alignment=TA_CENTER)
    ))

    doc.build(story)
    print(f"PDF generated: {output_path}")
    return output_path